import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

// Function to generate random password
function generateRandomPassword(length: number = 16): string {
  const charset = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@#$%^&*';
  const values = crypto.getRandomValues(new Uint8Array(length));
  return Array.from(values)
    .map((val) => charset[val % charset.length])
    .join('');
}

async function main() {
  console.log('🌱 Starting database seed...');

  // Create admin user
  const adminPassword = process.env.ADMIN_PASSWORD || generateRandomPassword(20);
  const hashedPassword = await bcrypt.hash(adminPassword, 10);
  const admin = await prisma.user.upsert({
    where: { email: 'admin@jewellery.com' },
    update: {},
    create: {
      email: 'admin@jewellery.com',
      name: 'Admin User',
      password: hashedPassword,
      phone: '+919876543210',
      role: 'ADMIN',
    },
  });

  console.log('✅ Admin user created:', admin.email);
  if (!process.env.ADMIN_PASSWORD) {
    console.log('⚠️  IMPORTANT: Admin password generated, save this:', adminPassword);
    console.log('   Password:', adminPassword);
  }

  // Create test user (only in development)
  if (process.env.NODE_ENV === 'development') {
    const testUserPassword = process.env.TEST_USER_PASSWORD || generateRandomPassword(12);
    const userPassword = await bcrypt.hash(testUserPassword, 10);
    const user = await prisma.user.upsert({
      where: { email: 'user@example.com' },
      update: {},
      create: {
        email: 'user@example.com',
        name: 'Test User',
        password: userPassword,
        phone: '+919876543211',
        role: 'USER',
      },
    });

    console.log('✅ Test user created:', user.email);
    if (!process.env.TEST_USER_PASSWORD) {
      console.log('⚠️  Test user password:', testUserPassword);
    }
  }

  // Create sample products
  const products = [
    {
      name: 'Beaumont Summit',
      slug: 'beaumont-summit',
      description: 'Elegant jewelry piece with exquisite craftsmanship.',
      price: 3300,
      originalPrice: 4500,
      image: '/products/beaumont-summit.jpg',
      images: ['/products/beaumont-summit.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 50,
      rating: 4.5,
      reviewCount: 12,
    },
    {
      name: 'Classic Gold Ring',
      slug: 'classic-gold-ring',
      description: 'Timeless classic gold ring for special occasions.',
      price: 4000,
      image: '/products/classic-gold-ring.jpg',
      images: ['/products/classic-gold-ring.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 30,
      rating: 4.0,
      reviewCount: 8,
    },
    {
      name: 'Pearl Necklace',
      slug: 'pearl-necklace',
      description: 'Beautiful pearl necklace that adds elegance to any outfit.',
      price: 3000,
      originalPrice: 4500,
      image: '/products/pearl-necklace.jpg',
      images: ['/products/pearl-necklace.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 25,
      rating: 5.0,
      reviewCount: 15,
    },
    {
      name: 'Diamond Earrings',
      slug: 'diamond-earrings',
      description: 'Stunning diamond earrings that sparkle with every movement.',
      price: 6000,
      image: '/products/diamond-earrings.jpg',
      images: ['/products/diamond-earrings.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 15,
      rating: 4.8,
      reviewCount: 20,
    },
    {
      name: 'Silver Bracelet',
      slug: 'silver-bracelet',
      description: 'Elegant silver bracelet with intricate design.',
      price: 3500,
      originalPrice: 4500,
      image: '/products/silver-bracelet.jpg',
      images: ['/products/silver-bracelet.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 40,
      rating: 4.2,
      reviewCount: 10,
    },
    {
      name: 'Rose Gold Set',
      slug: 'rose-gold-set',
      description: 'Complete rose gold jewelry set for special occasions.',
      price: 4500,
      image: '/products/rose-gold-set.jpg',
      images: ['/products/rose-gold-set.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 20,
      rating: 4.6,
      reviewCount: 18,
    },
    {
      name: 'Art Deco Pendant',
      slug: 'art-deco-pendant',
      description: 'Vintage-inspired art deco pendant with unique design.',
      price: 5500,
      image: '/products/art-deco-pendant.jpg',
      images: ['/products/art-deco-pendant.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 12,
      rating: 5.0,
      reviewCount: 25,
    },
    {
      name: 'Vintage Brooch',
      slug: 'vintage-brooch',
      description: 'Charming vintage brooch with intricate details.',
      price: 2000,
      originalPrice: 5500,
      image: '/products/vintage-brooch.jpg',
      images: ['/products/vintage-brooch.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 35,
      rating: 4.3,
      reviewCount: 7,
    },
    {
      name: 'Emerald Engagement Ring',
      slug: 'emerald-engagement-ring',
      description: 'Stunning emerald engagement ring with diamond accents.',
      price: 8500,
      originalPrice: 12000,
      image: '/products/emerald-engagement-ring.jpg',
      images: ['/products/emerald-engagement-ring.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 8,
      rating: 5.0,
      reviewCount: 22,
    },
    {
      name: 'Platinum Wedding Band',
      slug: 'platinum-wedding-band',
      description: 'Classic platinum wedding band with modern finish.',
      price: 5000,
      image: '/products/platinum-wedding-band.jpg',
      images: ['/products/platinum-wedding-band.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 45,
      rating: 4.7,
      reviewCount: 35,
    },
    {
      name: 'Sapphire Tennis Bracelet',
      slug: 'sapphire-tennis-bracelet',
      description: 'Luxurious sapphire tennis bracelet with white gold setting.',
      price: 12000,
      image: '/products/sapphire-tennis-bracelet.jpg',
      images: ['/products/sapphire-tennis-bracelet.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 6,
      rating: 5.0,
      reviewCount: 28,
    },
    {
      name: 'Gold Chain Necklace',
      slug: 'gold-chain-necklace',
      description: 'Bold gold chain necklace for modern style.',
      price: 4500,
      originalPrice: 6500,
      image: '/products/gold-chain-necklace.jpg',
      images: ['/products/gold-chain-necklace.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 28,
      rating: 4.4,
      reviewCount: 16,
    },
    {
      name: 'Ruby and Diamond Ring',
      slug: 'ruby-diamond-ring',
      description: 'Exquisite ruby ring surrounded by brilliant diamonds.',
      price: 9500,
      image: '/products/ruby-diamond-ring.jpg',
      images: ['/products/ruby-diamond-ring.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 10,
      rating: 4.9,
      reviewCount: 30,
    },
    {
      name: 'Silver Cuff Links',
      slug: 'silver-cuff-links',
      description: 'Elegant silver cuff links for formal occasions.',
      price: 2500,
      image: '/products/silver-cuff-links.jpg',
      images: ['/products/silver-cuff-links.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 60,
      rating: 4.5,
      reviewCount: 12,
    },
    {
      name: 'Onyx Pendant',
      slug: 'onyx-pendant',
      description: 'Striking onyx pendant with silver chain.',
      price: 2800,
      originalPrice: 4000,
      image: '/products/onyx-pendant.jpg',
      images: ['/products/onyx-pendant.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 32,
      rating: 4.3,
      reviewCount: 9,
    },
    {
      name: 'Titanium Watch',
      slug: 'titanium-watch',
      description: 'Modern titanium watch with minimalist design.',
      price: 7500,
      image: '/products/titanium-watch.jpg',
      images: ['/products/titanium-watch.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 18,
      rating: 4.6,
      reviewCount: 24,
    },
    {
      name: 'Crystal Drop Earrings',
      slug: 'crystal-drop-earrings',
      description: 'Dazzling crystal drop earrings with intricate design.',
      price: 3200,
      image: '/products/crystal-drop-earrings.jpg',
      images: ['/products/crystal-drop-earrings.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 38,
      rating: 4.4,
      reviewCount: 14,
    },
    {
      name: 'Gold Signet Ring',
      slug: 'gold-signet-ring',
      description: 'Classic gold signet ring with personalized engraving option.',
      price: 3800,
      originalPrice: 5500,
      image: '/products/gold-signet-ring.jpg',
      images: ['/products/gold-signet-ring.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 42,
      rating: 4.2,
      reviewCount: 11,
    },
    {
      name: 'Diamond Solitaire Necklace',
      slug: 'diamond-solitaire-necklace',
      description: 'Classic diamond solitaire necklace on elegant chain.',
      price: 15000,
      image: '/products/diamond-solitaire-necklace.jpg',
      images: ['/products/diamond-solitaire-necklace.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 5,
      rating: 5.0,
      reviewCount: 42,
    },
    {
      name: 'Silver Pendant Chain',
      slug: 'silver-pendant-chain',
      description: 'Versatile silver pendant chain for everyday wear.',
      price: 2200,
      image: '/products/silver-pendant-chain.jpg',
      images: ['/products/silver-pendant-chain.jpg'],
      category: 'unisex',
      inStock: true,
      stockQuantity: 55,
      rating: 4.1,
      reviewCount: 19,
    },
    {
      name: 'Rose Gold Hoop Earrings',
      slug: 'rose-gold-hoop-earrings',
      description: 'Trendy rose gold hoop earrings for contemporary style.',
      price: 2900,
      originalPrice: 4200,
      image: '/products/rose-gold-hoop-earrings.jpg',
      images: ['/products/rose-gold-hoop-earrings.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 48,
      rating: 4.5,
      reviewCount: 26,
    },
    {
      name: 'Tungsten Wedding Ring',
      slug: 'tungsten-wedding-ring',
      description: 'Durable tungsten wedding ring with brushed finish.',
      price: 3200,
      image: '/products/tungsten-wedding-ring.jpg',
      images: ['/products/tungsten-wedding-ring.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 52,
      rating: 4.6,
      reviewCount: 33,
    },
    {
      name: 'Pearl Drop Earrings',
      slug: 'pearl-drop-earrings',
      description: 'Elegant pearl drop earrings with gold accents.',
      price: 4100,
      image: '/products/pearl-drop-earrings.jpg',
      images: ['/products/pearl-drop-earrings.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 22,
      rating: 4.8,
      reviewCount: 31,
    },
    {
      name: 'Sterling Silver Ring Set',
      slug: 'sterling-silver-ring-set',
      description: 'Complete sterling silver ring set with matching designs.',
      price: 3600,
      originalPrice: 5200,
      image: '/products/sterling-silver-ring-set.jpg',
      images: ['/products/sterling-silver-ring-set.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 15,
      rating: 4.4,
      reviewCount: 17,
    },
    {
      name: 'Gold Coin Pendant',
      slug: 'gold-coin-pendant',
      description: 'Authentic gold coin pendant with chain.',
      price: 5500,
      image: '/products/gold-coin-pendant.jpg',
      images: ['/products/gold-coin-pendant.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 14,
      rating: 4.7,
      reviewCount: 13,
    },
    {
      name: 'Amethyst Statement Ring',
      slug: 'amethyst-statement-ring',
      description: 'Bold amethyst statement ring with gold setting.',
      price: 4800,
      originalPrice: 6800,
      image: '/products/amethyst-statement-ring.jpg',
      images: ['/products/amethyst-statement-ring.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 11,
      rating: 4.5,
      reviewCount: 21,
    },
    {
      name: 'Leather Band Watch',
      slug: 'leather-band-watch',
      description: 'Classic leather band watch with stainless steel case.',
      price: 4200,
      image: '/products/leather-band-watch.jpg',
      images: ['/products/leather-band-watch.jpg'],
      category: 'men',
      inStock: true,
      stockQuantity: 36,
      rating: 4.6,
      reviewCount: 29,
    },
    {
      name: 'Moonstone Pendant',
      slug: 'moonstone-pendant',
      description: 'Mystical moonstone pendant with silver chain.',
      price: 3400,
      image: '/products/moonstone-pendant.jpg',
      images: ['/products/moonstone-pendant.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 27,
      rating: 4.3,
      reviewCount: 8,
    },
    {
      name: 'Diamond Stud Earrings',
      slug: 'diamond-stud-earrings',
      description: 'Timeless diamond stud earrings in platinum setting.',
      price: 11000,
      originalPrice: 15000,
      image: '/products/diamond-stud-earrings.jpg',
      images: ['/products/diamond-stud-earrings.jpg'],
      category: 'women',
      inStock: true,
      stockQuantity: 9,
      rating: 5.0,
      reviewCount: 47,
    },
    {
      name: 'Copper Bracelet',
      slug: 'copper-bracelet',
      description: 'Handcrafted copper bracelet with natural patina.',
      price: 1800,
      image: '/products/copper-bracelet.jpg',
      images: ['/products/copper-bracelet.jpg'],
      category: 'unisex',
      inStock: true,
      stockQuantity: 65,
      rating: 3.9,
      reviewCount: 6,
    },
  ];

  for (const product of products) {
    const created = await prisma.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
    console.log(`✅ Product created: ${created.name}`);
  }

  console.log('🎉 Database seeded successfully!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
